site_name: Timerdo
repo_url: https://github.com/caiomts/timerdo
repo_name: caiomts/timerdo
edit_uri: edit/master/docs/

nav:
  - "Home": 
      - index.md
      - install.md
  - "Getting Started":
    - start.md
  - "Tutorial - User Guide":
    - tutorial_1.md
    - tutorial_2.md
  - "CLI Reference":
      - cli_reference.md


theme:
  features:
    - content.tabs.link
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  palette:
    - scheme: default
      primary: deep orange
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: deep purple
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

  features:
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.action.view
    - navigation.indexes

markdown_extensions:
  - attr_list
  - md_in_html
  - abbr
  - admonition
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/caiomts
      name: github.com/caiomts

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/caiomts/
      name: in/caiomts/

    - icon: material/web
      link: https://caiomts.github.io/
      name: caiomts.github.io

extra_css:
  - stylesheets/extra.css