name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Bootstrap
        run: scripts/bootstrap.sh
      - name: Publish
        env:
          FLIT_USERNAME: ${{ secrets.FLIT_USERNAME }}
          FLIT_PASSWORD: ${{ secrets.FLIT_PASSWORD }}
        run: . ./scripts/publish.sh